---
title: "Qualitative Assumptions log"
date: now
execute:
  echo: false
format:
  html:
    embed-resources: true
    toc: true
    toc-title: "Contents"
    toc-location: left
    html-math-method: katex
---
```{python}
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

assumptions = pd.read_excel("D:\\git_demo\\Assumptions_and_decisions/Qualitative_assumptions/assumptions_and_decision_log_template.xlsx", sheet_name="assumptions")
```


This log contains a list of assumptions used in this analysis.

## Definitions

Assumptions are red, amber or green (RAG) rated according to the following definitions for quality and impact (would replace this table with quality rating in our template)[^1]:

| RAG rating | Assumption quality | Assumption impact |
|------------|--------------------|-------------------|
| GREEN | Reliable assumption, well understood and/or documented; anything up to a validated & recent set of actual data. | Marginal assumptions; their changes have no or limited impact on the outputs.  |
| AMBER | Some evidence to support the assumption; may vary from a source with poor methodology to a good source that is a few years old. | Assumptions with a relevant, even if not critical, impact on the outputs. |
| RED   | Little evidence to support the assumption; may vary from an opinion to a limited data source with poor methodology. | Core assumptions of the analysis; the output would be drastically affected by their change. |

[^1]: With thanks to the Home Office Analytical Quality Assurance team for these definitions. 

## Assumptions

This analysis contains the following assumptions:

### Assumption 1: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[0, 'Location in code/publication']}  
* **Quality**: {assumptions.at[0, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[0, 'Sensitivity Score']}  
Description: {assumptions.at[0, 'Plain English description of assumption']}  """))
``` 

### Assumption 2: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[1, 'Location in code/publication']}  
* **Quality**: {assumptions.at[1, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[1, 'Sensitivity Score']}  
Description: {assumptions.at[1, 'Plain English description of assumption']}  """))
``` 

### Assumption 3: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[2, 'Location in code/publication']}  
* **Quality**: {assumptions.at[2, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[2, 'Sensitivity Score']}  
Description: {assumptions.at[2, 'Plain English description of assumption']}  """))
``` 

### Assumption 4: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[3, 'Location in code/publication']}  
* **Quality**: {assumptions.at[3, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[3, 'Sensitivity Score']}  
Description: {assumptions.at[3, 'Plain English description of assumption']}  """))
``` 

### Assumption 5: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[4, 'Location in code/publication']}  
* **Quality**: {assumptions.at[4, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[4, 'Sensitivity Score']}  
Description: {assumptions.at[4, 'Plain English description of assumption']}  """))
``` 

### Assumption 6: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[5, 'Location in code/publication']}  
* **Quality**: {assumptions.at[5, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[5, 'Sensitivity Score']}  
Description: {assumptions.at[5, 'Plain English description of assumption']}  """))
``` 

### Assumption 7: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[6, 'Location in code/publication']}  
* **Quality**: {assumptions.at[6, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[6, 'Sensitivity Score']}  
Description: {assumptions.at[6, 'Plain English description of assumption']}  """))
``` 

### Assumption 8: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[7, 'Location in code/publication']}  
* **Quality**: {assumptions.at[7, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[7, 'Sensitivity Score']}  
Description: {assumptions.at[7, 'Plain English description of assumption']}  """))
``` 

### Assumption 9: Title of assumption

```{python}
display(Markdown(f"""   
* **Location in code/publication**: {assumptions.at[8, 'Location in code/publication']}  
* **Quality**: {assumptions.at[8, 'Quality Rating']}  
* **Senstivity Score**: {assumptions.at[8, 'Sensitivity Score']}  
Description: {assumptions.at[8, 'Plain English description of assumption']}  """))
``` 


