---
title: "Quality Assurance Report"
author: "Shazmeen Maroof"
date: now
execute:
  echo: false
format:
  html:
    embed-resources: true
    toc: true
    toc-title: "Contents"
    toc-location: left
    html-math-method: katex
---

```{python}
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

housing_introduction = pd.read_excel("D:\\git_demo\\Generic_qa_report/Housing_data.xlsx", sheet_name="introduction")

housing_sale_counts = pd.read_excel("D:\\git_demo\\Generic_qa_report/Housing_data.xlsx", sheet_name="sale_counts")

housing_median_sale_price = pd.read_excel("D:\\git_demo\\Generic_qa_report/Housing_data.xlsx", sheet_name="median_sale_price")
```

## Introduction

```{python}
display(Markdown(f""" The title of the dataset is {housing_introduction.at[0, 'Column_b']}. {housing_introduction.at[1, 'Column_b']}. The data has been taken from {housing_introduction.at[2, 'Column_b']}. The data is published {housing_introduction.at[3, 'Column_b']}. The data spans from {housing_introduction.at[4, 'Column_b']}. The data limitations are {housing_introduction.at[5, 'Column_b']}. The data is published {housing_introduction.at[7, 'Column_b']} confidence intervals. {housing_introduction.at[8, 'Column_b']}.  """))
``` 


## Summary of tests performed

There are “nrows” and “ncolumns” in the dataset. We have performed "n" tests on the data. The data has passed "n" tests and failed "n". 

## Data cleaning tests  


## Table 1: List of tests (Test_number, Description, Long_description, Status, Status_description)  


## List of failed tests with their location  

Test 1:

```{python}
def test_sum_dwellings():
    print("Description: Checks if sum of variables equals total.")  
    print("Data specific description: Checks if sum of detahced, semi-detached, terraced and flats equals all dwelling types")  
    if housing_sale_counts['All_dwelling_types'].all != (housing_sale_counts['Detached'] + housing_sale_counts['Semi-detached'] + housing_sale_counts['Terraced'] + housing_sale_counts['Flats']).all:
        print("Status: Fail. A fail means sum of varaibles do not equal total.")
        return False
    else:
        print("Status: Pass. A pass means sum of variables equals total.")
        return True
print (test_sum_dwellings())
```

Test 2: Flats should be lesser than all other dwelling types  

```{python}
def test_num_flats():
    print("Description: Checks if values of a variable are always less than other.")  
    print("Data specific description: Checks if the number of flats are lesser than the number of all other dwelling types in all councils.")  
    if all(housing_sale_counts['Detached' or 'Semi-detached' or 'Terraced']) > all(housing_sale_counts['Flats']): 
        print("Status: Pass. A pass means number of flats are less than all other dwelling types in all councils.")
        return True
    else:
        print("Status: Fail. A fail means number of flats are not less than all other dwelling types in atleast one council.")
        return False
print (test_num_flats())
```

Test 3: 
Description: Checks if any of the variables in the dataset has a negative value.
Data specific description: Checks if the data on sales of detahced, semi-detached, terraced and flats has a negative value. 
```{python}
test_neg = ((housing_sale_counts['Detached' or 'Semi-detached' or 'Terraced' or 'Flats']) < 0).any().any()
print ("Status:")
print (test_neg)
print("Status description: A true means there is no negative values (Pass). A false means there is a negative value (Fail).")
```


Test 4: 
Description: Checks if any of the variables in the dataset has a negative value.
Data specific description: Checks if the data on prices of detahced, semi-detached, terraced and flats has a negative value. 
```{python}
test_neg = ((housing_median_sale_price['Detached' or 'Semi-detached' or 'Terraced' or 'Flats']) < 0).any().any()
print ("Status:")
print (test_neg)
print("Status description: A true means there is no negative values (Pass). A false means there is a negative value (Fail).")
```

Test 5: There shouldn’t be an alphabet in sales  
```{python}
```

Test 6: There shouldn’t be an alphabet in prices  
```{python}
```

Test 7a: Are there any missing values?  
Test 7b: If yes, how many?
```{python}
```

Test 8: A local authority name should only appear 5 times in data  
```{python}
```

Test 9:	A local authority code should only appear 5 times in data  
```{python}
```
Test 10: Detect outliers  
```{python}
```

How I want it like: 
Test 1: 
Description: Checks if sum of columns equals total. 
Long_description: Checks if sum of detahced, semi-detached, terraced and flats equals all dwelling types.
Status: Pass/Fail
Status_description: A pass means sum of columns equals total. A fail means sum of columns do not equals total.
If fail, location of failure: 
``` 

Failed: Error in observation 10

Test 2: Flats should be lesser than all other dwelling types  
Failed: Error ...

Test 3: There shouldn’t be a negative value in sales  
Passed 

Test 4: There shouldn’t be a negative value in prices  
Passed:

Test 5: There shouldn’t be an alphabet in sales  


Test 6: There shouldn’t be an alphabet in prices  

Test 7a: Are there any missing values?  
Test 7b: If yes, how many?

Test 8: A local authority name should only appear 5 times in data  


Test 9:	A local authority code should only appear 5 times in data  

Test 10: Detect outliers  

## Checking characteristics of the data

Test 1: Plot trend of sales and prices by dwelling types

Test 2: What does the data distribution look like? 

Test 3: Is there any correlation between tpe of dwellings and house price?
