---
title: "Understanding Joe Perry's code on Linear Regression Quality Assurance"
author: "Shazmeen Maroof"
execute:
  echo: false
format:
  html:
    embed-resources: true
    toc: true
    toc-title: "Contents"
    toc-location: left
    html-math-method: katex
---

```{python}
#| tags: [parameters]
model = None
theta_0 = None
theta_1 = None
pipeline_runtime = None
x_data = None
y_data = None
y_predicted = None
residuals = None
w_stat = None
p_value = None
config = None
r_squared = None
```

## Introduction

This QA report is for a univariate linear regression pipeline run on the possum dataset taken from Kaggle. (Link to data: https://www.kaggle.com/datasets/abrambeyer/openintro-possum). The model aims to understand the relationship between posumm's head length and its total length. The report is created using Quarto, RStudio's multi-language version of R Markdown.

## Pipeline Configuration and Model Summary

This section shows the pipeline configuration used in generating this report. The convergence threshold determines when the model is considered to have finished training, and theta_0 and theta_1 are the regression model parameters, namely the y-intercept and gradient, respectively. The value of convergane threshold has been set to 1e-06. Learning rate has been set as 0.001. The values of theta_0 and theta_1 are set to 0. Below we see the sumary output of regression analysis. 

```{python}
from IPython.display import display, Markdown
from tabulate import tabulate
import pandas as pd
import numpy as np

import statsmodels.api as sm
import matplotlib.pyplot as plt 
import seaborn as sns
import datetime
import yaml
from quarto import render
import plotly.express as px
from statsmodels.graphics.gofplots import qqplot
import matplotlib.pyplot as plt


# Read the CSV file on possum and view some data points
possum = pd.read_csv("C:\\Users\\maroos/Downloads/possum.csv")
possum

# Create x and y variables
x = possum['skullw']
y = possum['hdlngth']

#add constant to predictor variables
x = sm.add_constant(x)

#fit linear regression model
model = sm.OLS(y, x)
results = model.fit()
print(results.summary())
```

## Model Performance

```{python}
display(Markdown(f"""The model has a coefficient of determination (R^2) of {results.rsquared:.5}. Below we see the best fit line of the model plotted alongside the data."""))
```

```{python}
sns.regplot(data=possum, x="skullw", y="hdlngth")
```

One of the assumptions of linear regression is that the errors are normally distributed. 
We may visually check this by plotting the errors/residuals against the model's predicted 
y-values. We want the residuals to be randomly distributed about zero, regardless of the 
size of the fitted/predicted values. Structure in the residual plot can reveal a violation of linear regression assumptions.

```{python}
sns.residplot(data=possum, x="skullw", y="hdlngth")
```

A QQ plot also allows us to assess whether the residuals are likely to have come from a normal distribution.

```{python}
sm.qqplot(results.resid, line='45')
```